spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/auth/realms/receipt-sharing
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: receipt-sharing-gateway
            client-secret: f1272f8c-e377-4b73-acb2-36a3ea66d161
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users, /users/**
          filters:
            - name: CircuitBreaker
              args:
                name: serviceA
                fallbackUri: forward:/fallback


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        slowCallDurationThreshold: 200
        slowCallRateThreshold: 80
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
        ignoreExceptions:
          - java.lang.IllegalStateException
    instances:
      serviceA:
        baseConfig: default

logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG