server:
  port: 8081
spring:
  application:
    name: user-service
  data:
    mongodb:
      auto-index-creation: true
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/receipt-sharing
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG